### ISSUE TITLE
Compiling failed on MacOS

### ISSUE THREAD

**Issue by vschwaberow** [BSI-Bund/TaSK#3]
[ 97%] Building C object CMakeFiles/minigzip.dir/test/minigzip.o
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:351:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void error(msg)
     ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:362:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void gz_compress(in, out)
     ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:430:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void gz_uncompress(in, out)
     ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:457:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void file_compress(file, mode)
     ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:496:6: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
void file_uncompress(file)
     ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:556:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int main(argc, argv)
    ^
/Users/volker/src/TaSK/tlstesttool/build/EP_ZLIB-prefix/src/EP_ZLIB/test/minigzip.c:556:5: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
7 warnings generated.
[100%] Linking C executable minigzip
[100%] Built target minigzip
[ 37%] Performing install step for 'EP_ZLIB'
[ 44%] Built target zlib
[ 88%] Built target zlibstatic
[ 94%] Built target example
[100%] Built target minigzip
Install the project...
-- Install configuration: ""
-- Installing: /Users/volker/src/TaSK/tlstesttool/build/EP_BASE/lib/libz.a
-- Installing: /Users/volker/src/TaSK/tlstesttool/build/EP_BASE/include/zconf.h
-- Installing: /Users/volker/src/TaSK/tlstesttool/build/EP_BASE/include/zlib.h
-- Installing: /Users/volker/src/TaSK/tlstesttool/build/EP_BASE/share/man/man3/zlib.3
-- Installing: /Users/volker/src/TaSK/tlstesttool/build/EP_BASE/share/pkgconfig/zlib.pc
[ 40%] Completed 'EP_ZLIB'
[ 40%] Built target EP_ZLIB
[ 42%] Creating directories for 'EP_MBEDTLS'
[ 45%] Performing download step (download, verify and extract) for 'EP_MBEDTLS'
-- Downloading...
   dst='/Users/volker/src/TaSK/tlstesttool/build/EP_MBEDTLS-prefix/src/mbedtls-2.2.1.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/mbedtls-2.2.1.tar.gz'
-- verifying file...
       file='/Users/volker/src/TaSK/tlstesttool/build/EP_MBEDTLS-prefix/src/mbedtls-2.2.1.tar.gz'
-- Downloading... done
-- extracting...
     src='/Users/volker/src/TaSK/tlstesttool/build/EP_MBEDTLS-prefix/src/mbedtls-2.2.1.tar.gz'
     dst='/Users/volker/src/TaSK/tlstesttool/build/EP_MBEDTLS-prefix/src/EP_MBEDTLS'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 47%] No update step for 'EP_MBEDTLS'
[ 50%] Performing patch step for 'EP_MBEDTLS'
patching file 'include/mbedtls/config.h'
patching file 'include/mbedtls/ssl.h'
patching file 'library/ssl_cli.c'
patching file 'include/mbedtls/ssl.h'
patching file 'library/ssl_cli.c'
patching file 'library/debug.c'
patching file 'library/ssl_cli.c'
patching file 'library/ssl_cli.c'
patching file 'include/mbedtls/ssl.h'
1 out of 1 hunks failed--saving rejects to 'include/mbedtls/ssl.h.rej'
patching file 'library/ssl_cli.c'
patching file 'library/ssl_srv.c'
patching file 'library/ssl_tls.c'
make[2]: *** [EP_MBEDTLS-prefix/src/EP_MBEDTLS-stamp/EP_MBEDTLS-patch] Error 1
make[1]: *** [CMakeFiles/EP_MBEDTLS.dir/all] Error 2
make: *** [all] Error 2

OS: MacOS 13.0 Ventura
clang --version
Homebrew clang version 15.0.6
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

**Comment by nb-2020** [comment]
Hi, thanks for reporting the issue. At the moment, we do not support MacOS. 
Currently, we are supporting the following Operating Systems: 
- Operating System: x86-64 Linux Distribution, e.g. Ubuntu 20.04 (https://ubuntu.com/download/desktop) or Debian 10 (https://www.debian.org/index.de.html)
