### ISSUE TITLE
Doku of TLS Test Tool

### ISSUE THREAD

**Issue by acbekoac** [BSI-Bund/TaSK#6]
on Debain it's been build with 

./tlstesttool/build/EP_BASE/bin/openssl version
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)

./tlstesttool/build/EP_BASE/bin/openssl ciphers -v
TLS_AES_256_GCM_SHA384         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(256)            Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256   TLSv1.3 Kx=any      Au=any   Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256         TLSv1.3 Kx=any      Au=any   Enc=AESGCM(128)            Mac=AEAD

but I cant find the config paramter in section "2.2.5 TLS options" of the doku
I guess it might be (3,4) - would be nice if added

**Comment by nb-2020** [comment]
Hi, thanks for reporting the issue. It seems that the tlsVersion 1.3 (3,4) is missing in the TLS options. We will provide a fix in one of the next releases.

**Comment by rk8129406** [comment]
Issue has been fixed with the 1.0.1 release.
