### ISSUE TITLE
shadow variable

### ISSUE THREAD

**Issue by maddin200** [BSI-Bund/TaSK#8]
/tlstesttool/src/tls/mbedtls/TlsSession.cpp line 275
code:
	const auto result = mbedtls_ssl_fetch_input(&ssl, 5);
	const bool msgHeaderIndicatesAlert = (0 == result) && (MBEDTLS_SSL_MSG_ALERT == ssl.in_hdr[0]);
	if (msgHeaderIndicatesAlert || forceRead) {
		const auto result = mbedtls_ssl_read_record(&ssl);  // <- shadow variable

**Comment by nb-2020** [comment]
Hi, thanks for reporting the issue. We agree with your analysis and will provide a fix in one of the next releases.

**Comment by rk8129406** [comment]
Issue has been fixed with the 1.0.1 release.
